use_frameworks!

def elValidator_pods
    pod 'ElValidator', :git => 'https://github.com/dk53/ElValidator.git'
end

target 'ElValidator_Example' do
    elValidator_pods
end

target 'ElValidator_Tests' do
    elValidator_pods
end
